# /etc/fail2ban/filter.d/vps-mysql-auth.conf
[Definition]
failregex = ^.* \[Warning\] Access denied for user '.*'@'<HOST>' (using password: (YES|NO|.*))$
            ^.* \[Warning\] IP address '.*' could not be resolved: .*$
ignoreregex = 
