[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/{{APP_DOMAIN}}/current/artisan queue:work --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user={{APP_USER}}
numprocs=2
redirect_stderr=true
stdout_logfile=/var/log/supervisor/ssr-{{APP_DOMAIN}}.log

stopwaitsecs=3600
stopasgroup=true
killasgroup=true
