[program:ssr-{{APP_DOMAIN}}]
process_name=%(program_name)s
command=php /var/www/{{APP_DOMAIN}}/current/artisan inertia:start-ssr
autostart=true
autorestart=true
user={{APP_USER}}
redirect_stderr=true
stdout_logfile=/var/www/{{APP_DOMAIN}}/shared/storage/logs/ssr.log
stopwaitsecs=3600
environment=NODE_PORT={{SSR_PORT}}
