[program:laravel-reverb]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/{{APP_DOMAIN}}/current/artisan reverb:start --host="0.0.0.0" --port={{SUPERVISOR_REVERB_PORT}}
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user={{APP_USER}}
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/supervisor/laravel-reverb.log
stopwaitsecs=3600
